node:
    name: B
    hostname: localhost
    port: 8001
    directory: tmp/b/
    neighbors:
      - hostname: localhost
        port: 8000
      - hostname: localhost
        port: 8002
    save_files: true