node:
    name: C
    hostname: localhost
    port: 8002
    directory: tmp/c/
    neighbors:
      - hostname: localhost
        port: 8000
      - hostname: localhost
        port: 8001
    save_files: true